#
# Copyright (C) 2019 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Display
PRODUCT_PROPERTY_OVERRIDES += \
    ro.sf.lcd_density=560

# Init (Android project name autogenerated by vendor_buildinfo.sh as a system.prop)
PRODUCT_PROPERTY_OVERRIDES += \
ro.boot.project_name=18821 \
ro.vendor.boot.project_name=18821
